from pathlib import Path


def replace(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text()
    if old not in text:
        raise SystemExit(f"missing in {path}: {old!r}")
    p.write_text(text.replace(old, new, 1))


replace('internal/serve/search_saved.go', 'type SuggestionsResponse struct {\n\tItems []TagDTO `json:"items"`\n}\n', 'type MetaTagDTO struct {\n\tName string `json:"name"`\n\tSyntax string `json:"syntax"`\n\tHint string `json:"hint"`\n\tRequiresValue bool `json:"requires_value"`\n}\n\ntype SuggestionsResponse struct {\n\tItems []TagDTO `json:"items"`\n\tMetaTags []MetaTagDTO `json:"meta_tags"`\n}\n')
replace('internal/serve/search_saved.go', 'func matchingMetaTagSuggestions(prefix string) []TagDTO {', 'func metaTagDTOs() []MetaTagDTO {\n\tdefinitions := query.MetaTags()\n\titems := make([]MetaTagDTO, 0, len(definitions))\n\tfor _, definition := range definitions {\n\t\titems = append(items, MetaTagDTO{Name: definition.Name, Syntax: definition.Syntax, Hint: definition.Hint, RequiresValue: definition.RequiresValue})\n\t}\n\treturn items\n}\n\nfunc matchingMetaTagSuggestions(prefix string) []TagDTO {')
replace('internal/serve/search_saved.go', 'writeJSON(w, http.StatusOK, SuggestionsResponse{Items: items})', 'writeJSON(w, http.StatusOK, SuggestionsResponse{Items: items, MetaTags: metaTagDTOs()})')

replace('frontend/src/lib/search/specialSuggestions.ts', 'metaTags: Array<{ name: string; value?: string }> = []', 'metaTags: Array<{ syntax: string; hint: string; requires_value: boolean }> = []')
replace('frontend/src/lib/search/specialSuggestions.ts', 'const syntax = metaTag.name.trim();', 'const syntax = metaTag.syntax.trim();')
replace('frontend/src/lib/search/specialSuggestions.ts', "const requiresValue = syntax.endsWith(':');\n    if (requiresValue) {", 'if (metaTag.requires_value) {')
replace('frontend/src/lib/search/specialSuggestions.ts', "hint: metaTag.value || 'query',", "hint: metaTag.hint || 'query',")
replace('frontend/src/lib/search/specialSuggestions.ts', "hint: metaTag.value || 'query'", "hint: metaTag.hint || 'query'")

replace('frontend/src/lib/components/SearchBar.svelte', 'type SuggestionLike = { name: string; value?: string; count?: number };', 'type SuggestionLike = { name: string; value?: string; count?: number };\n  type MetaTagLike = { syntax: string; hint: string; requires_value: boolean };')
replace('frontend/src/lib/components/SearchBar.svelte', '    suggestions,\n    tags,', '    suggestions,\n    metaTags,\n    tags,')
replace('frontend/src/lib/components/SearchBar.svelte', '    suggestions: SuggestionLike[];\n    tags: TagLike[];', '    suggestions: SuggestionLike[];\n    metaTags: MetaTagLike[];\n    tags: TagLike[];')
replace('frontend/src/lib/components/SearchBar.svelte', "  const tagItems = $derived(normalizeTags(tags, suggestions));\n  const metaTagItems = $derived(suggestions.filter((item) => item.name.startsWith('@')));\n  const groups = $derived(computeSuggestions(draft, tokens, tagItems, metaTagItems));", '  const tagItems = $derived(normalizeTags(tags, suggestions));\n  const groups = $derived(computeSuggestions(draft, tokens, tagItems, metaTags));')
replace('frontend/src/lib/components/SearchBar.svelte', '    metaTags: SuggestionLike[]', '    metaTags: MetaTagLike[]')

replace('frontend/src/lib/api/types.ts', "export type SuggestionsResponse = components['schemas']['SuggestionsResponse'];", "export type MetaTagDefinition = components['schemas']['MetaTag'];\nexport type SuggestionsResponse = components['schemas']['SuggestionsResponse'];")
replace('frontend/src/lib/components/AppShell.svelte', "import type { Job } from '$lib/api/types';", "import type { Job, MetaTagDefinition } from '$lib/api/types';")
replace('frontend/src/lib/components/AppShell.svelte', '    suggestions,\n    tags,', '    suggestions,\n    metaTags,\n    tags,')
replace('frontend/src/lib/components/AppShell.svelte', '    suggestions: Array<{ name: string; count?: number }>;\n    tags: TagLike[];', '    suggestions: Array<{ name: string; count?: number }>;\n    metaTags: MetaTagDefinition[];\n    tags: TagLike[];')
replace('frontend/src/lib/components/AppShell.svelte', '          {suggestions}\n          {tags}', '          {suggestions}\n          {metaTags}\n          {tags}')
replace('frontend/src/lib/components/AuthenticatedApp.svelte', '    suggestions={suggestionsQuery.data?.items ?? []}\n    tags={tagsQuery.data?.tags ?? []}', '    suggestions={suggestionsQuery.data?.items ?? []}\n    metaTags={suggestionsQuery.data?.meta_tags ?? []}\n    tags={tagsQuery.data?.tags ?? []}')

replace('docs/openapi.yaml', '''    SuggestionsResponse:\n      type: object\n      required: [items]\n      properties:\n        items:\n          type: array\n          items:\n            $ref: "#/components/schemas/Tag"\n''', '''    MetaTag:\n      type: object\n      required: [name, syntax, hint, requires_value]\n      properties:\n        name:\n          type: string\n        syntax:\n          type: string\n        hint:\n          type: string\n        requires_value:\n          type: boolean\n    SuggestionsResponse:\n      type: object\n      required: [items, meta_tags]\n      properties:\n        items:\n          type: array\n          items:\n            $ref: "#/components/schemas/Tag"\n        meta_tags:\n          type: array\n          description: Complete backend-owned catalog of supported query metatags.\n          items:\n            $ref: "#/components/schemas/MetaTag"\n''')
replace('internal/serve/openapi_test.go', '\tassertResponseSchemaRef(t, spec, "/search/suggestions", "get", "200", "#/components/schemas/SuggestionsResponse")', '\tassertResponseSchemaRef(t, spec, "/search/suggestions", "get", "200", "#/components/schemas/SuggestionsResponse")\n\tsuggestionRequired := stringSlice(t, schema(t, spec, "SuggestionsResponse")["required"])\n\tif !containsString(suggestionRequired, "meta_tags") {\n\t\tt.Fatalf("SuggestionsResponse must require meta_tags, got %+v", suggestionRequired)\n\t}\n\tmetaTagProps := stringMap(t, schema(t, spec, "MetaTag")["properties"])\n\tfor _, field := range []string{"name", "syntax", "hint", "requires_value"} {\n\t\tif _, ok := metaTagProps[field]; !ok {\n\t\t\tt.Fatalf("MetaTag schema missing %q", field)\n\t\t}\n\t}')

Path('internal/query/metatags_test.go').write_text('''package query\n\nimport (\n\t"strings"\n\t"testing"\n)\n\nfunc TestMetaTagCatalogAndParser(t *testing.T) {\n\tdefinitions := MetaTags()\n\tif len(definitions) != 2 {\n\t\tt.Fatalf("got %d metatags, want 2", len(definitions))\n\t}\n\tif definitions[0].Name != MetaTagTagged || definitions[1].Name != MetaTagFilenameContains {\n\t\tt.Fatalf("unexpected catalog: %+v", definitions)\n\t}\n\tparsed, err := ParseMetaTag(`@filename_contains:Summer 100%_Set`)\n\tif err != nil {\n\t\tt.Fatalf("parse filename metatag: %v", err)\n\t}\n\tif parsed.Value != `Summer 100%_Set` || !parsed.Definition.RequiresValue {\n\t\tt.Fatalf("unexpected parsed metatag: %+v", parsed)\n\t}\n\tif _, err := ParseMetaTag(`@filename_contains:`); err == nil {\n\t\tt.Fatal("expected empty filename_contains value to fail")\n\t}\n}\n\nfunc TestFilenameContainsBuildLocationsTargetsBasenameCaseInsensitivelyAndEscapesWildcards(t *testing.T) {\n\texpr, err := Parse(`@filename_contains:"100%_SET"`)\n\tif err != nil {\n\t\tt.Fatal(err)\n\t}\n\tif err := ValidateAST(expr); err != nil {\n\t\tt.Fatal(err)\n\t}\n\tqueryText, args := BuildLocations(expr, nil)\n\tif len(args) != 1 || args[0] != `%100\\%\\_SET%` {\n\t\tt.Fatalf("unexpected LIKE args: %#v", args)\n\t}\n\tfor _, fragment := range []string{"WITH RECURSIVE path_parts", "replace(path, char(92), '/')", "p.rest = ''", "lower(p.part) LIKE lower(?) ESCAPE '\\\\'"} {\n\t\tif !strings.Contains(queryText, fragment) {\n\t\t\tt.Fatalf("query missing %q: %s", fragment, queryText)\n\t\t}\n\t}\n}\n''')
Path('internal/serve/search_saved_metatags_test.go').write_text('''package serve\n\nimport "testing"\n\nfunc TestMetaTagDTOsExposeCompleteQueryCatalog(t *testing.T) {\n\titems := metaTagDTOs()\n\tif len(items) != 2 {\n\t\tt.Fatalf("got %d metatags, want 2", len(items))\n\t}\n\tif items[0].Syntax != "@tagged" || items[0].RequiresValue {\n\t\tt.Fatalf("unexpected tagged metadata: %+v", items[0])\n\t}\n\tif items[1].Syntax != "@filename_contains:" || !items[1].RequiresValue {\n\t\tt.Fatalf("unexpected filename metadata: %+v", items[1])\n\t}\n}\n''')
Path('frontend/src/lib/search/specialSuggestions.test.ts').write_text('''import { describe, expect, it } from 'vitest';\nimport { specialSearchSuggestions } from './specialSuggestions';\n\nconst metaTags = [\n  { syntax: '@tagged', hint: 'has tags', requires_value: false },\n  { syntax: '@filename_contains:', hint: 'filename contains', requires_value: true }\n];\n\ndescribe('specialSearchSuggestions', () => {\n  it('uses the backend catalog for metatags and hides them on unrelated input', () => {\n    expect(specialSearchSuggestions('@t', [], metaTags)).toEqual([\n      { commit: '@tagged', ns: '', val: '@tagged', hint: 'has tags' }\n    ]);\n    expect(specialSearchSuggestions('@f', [], metaTags)).toEqual([\n      { commit: '@filename_contains:', ns: '@filename_contains', val: '', hint: 'filename contains', partial: true }\n    ]);\n    expect(specialSearchSuggestions('artist', [], metaTags)).toEqual([]);\n  });\n\n  it('does not invent metatags when the backend catalog is empty', () => {\n    expect(specialSearchSuggestions('@t')).toEqual([]);\n    expect(specialSearchSuggestions('@f')).toEqual([]);\n  });\n\n  it('completes supported media kinds after type:', () => {\n    expect(specialSearchSuggestions('type:v', [], metaTags)).toEqual([\n      { commit: 'type:video', ns: 'type', val: 'video', hint: 'media type' }\n    ]);\n    expect(specialSearchSuggestions('type:', [], metaTags)).toHaveLength(5);\n  });\n\n  it('supports negation and excludes already committed exact expressions', () => {\n    expect(specialSearchSuggestions('-@t', [], metaTags)).toEqual([\n      { commit: '-@tagged', ns: '', val: '@tagged', hint: 'has tags' }\n    ]);\n    expect(specialSearchSuggestions('@t', ['@tagged'], metaTags)).toEqual([]);\n    expect(specialSearchSuggestions('type:v', ['type:video'], metaTags)).toEqual([]);\n  });\n});\n''')
