from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected one match, found {count}")
    p.write_text(text.replace(old, new, 1))


replace_once(
    "frontend/src/lib/components/AuthenticatedApp.svelte",
    "  import { createUploadWorkflow } from '$lib/state/uploadWorkflow.svelte';\n",
    "  import { createUploadWorkflow } from '$lib/state/uploadWorkflow.svelte';\n  import { createUploadTagReconciliationWave } from '$lib/state/uploadTagReconciliation';\n",
)
replace_once(
    "frontend/src/lib/components/AuthenticatedApp.svelte",
    "  const uploadTagSyncRuns = new Set<object>();\n",
    "  const uploadTagReconciliation = createUploadTagReconciliationWave(() => refreshUploadQueries(queryClient).catch(() => undefined));\n",
)
replace_once(
    "frontend/src/lib/components/AuthenticatedApp.svelte",
    '''  async function reconcileUploadItemTags(index: number) {\n    const item = upload.items[index];\n    if (!item?.tagSyncPending || !item.remoteFileID || uploadTagSyncRuns.has(item)) return;\n    const delta = upload.itemTagSyncDelta(index);\n    const operation = delta.add.length ? 'add' : delta.remove.length ? 'remove' : null;\n    if (!operation) {\n      upload.markItemTagSyncApplied(index, 'add', []);\n      return;\n    }\n    const changedTags = operation === 'add' ? delta.add : delta.remove;\n    const remoteFileID = item.remoteFileID;\n    uploadTagSyncRuns.add(item);\n    try {\n      await tagMutation.mutateAsync({ operation, body: { file_ids: [remoteFileID], tags: changedTags } });\n      const currentIndex = upload.items.indexOf(item);\n      if (currentIndex >= 0) upload.markItemTagSyncApplied(currentIndex, operation, changedTags);\n    } catch (error) {\n      const currentIndex = upload.items.indexOf(item);\n      if (currentIndex >= 0) upload.markItemTagSyncError(currentIndex, errorMessage(error));\n    } finally {\n      uploadTagSyncRuns.delete(item);\n      const currentIndex = upload.items.indexOf(item);\n      if (currentIndex >= 0 && item.tagSyncPending && item.remoteFileID && !item.tagSyncError) {\n        void reconcileUploadItemTags(currentIndex);\n      }\n    }\n  }\n''',
    '''  function reconcileUploadItemTags(index: number) {\n    const item = upload.items[index];\n    if (!item?.tagSyncPending || !item.remoteFileID) return;\n\n    void uploadTagReconciliation.run(item, async () => {\n      const currentIndex = upload.items.indexOf(item);\n      if (currentIndex < 0 || !item.tagSyncPending || !item.remoteFileID || item.tagSyncError) return false;\n\n      const delta = upload.itemTagSyncDelta(currentIndex);\n      const operation = delta.add.length ? 'add' : delta.remove.length ? 'remove' : null;\n      if (!operation) {\n        upload.markItemTagSyncApplied(currentIndex, 'add', []);\n        return false;\n      }\n\n      const changedTags = operation === 'add' ? delta.add : delta.remove;\n      const remoteFileID = item.remoteFileID;\n      try {\n        await new ApiClient($authState.csrfToken).mutateTags(operation, { file_ids: [remoteFileID], tags: changedTags });\n        const appliedIndex = upload.items.indexOf(item);\n        if (appliedIndex < 0) return false;\n        upload.markItemTagSyncApplied(appliedIndex, operation, changedTags);\n        return item.tagSyncPending && Boolean(item.remoteFileID) && !item.tagSyncError;\n      } catch (error) {\n        const failedIndex = upload.items.indexOf(item);\n        if (failedIndex >= 0) upload.markItemTagSyncError(failedIndex, errorMessage(error));\n        return false;\n      }\n    });\n  }\n''',
)

Path("frontend/src/lib/state/uploadTagReconciliation.ts").write_text('''export type UploadTagReconciliationStep = () => Promise<boolean>;\n\nexport function createUploadTagReconciliationWave(onSettled: () => Promise<void> | void) {\n  const runs = new Map<object, Promise<void>>();\n  let generation = 0;\n  let refreshedGeneration = 0;\n  let refreshRun: Promise<void> | null = null;\n\n  async function refreshWhenIdle() {\n    if (refreshRun) return refreshRun;\n\n    const run = (async () => {\n      while (runs.size === 0 && refreshedGeneration < generation) {\n        const targetGeneration = generation;\n        try {\n          await onSettled();\n        } finally {\n          refreshedGeneration = targetGeneration;\n        }\n      }\n    })();\n    refreshRun = run;\n    try {\n      await run;\n    } finally {\n      if (refreshRun === run) refreshRun = null;\n      if (runs.size === 0 && refreshedGeneration < generation) void refreshWhenIdle();\n    }\n  }\n\n  function run(key: object, step: UploadTagReconciliationStep) {\n    const existing = runs.get(key);\n    if (existing) return existing;\n\n    generation += 1;\n    const task = (async () => {\n      try {\n        while (await step()) {\n          // Keep one row inside the same wave while edits arrive during an in-flight mutation.\n        }\n      } finally {\n        runs.delete(key);\n        if (runs.size === 0) await refreshWhenIdle();\n      }\n    })();\n    runs.set(key, task);\n    return task;\n  }\n\n  return {\n    run,\n    isRunning: (key: object) => runs.has(key)\n  };\n}\n''')

Path("frontend/src/lib/state/uploadTagReconciliation.test.ts").write_text('''import { describe, expect, it } from 'vitest';\nimport { createUploadTagReconciliationWave } from './uploadTagReconciliation';\n\nfunction deferred() {\n  let release!: () => void;\n  const promise = new Promise<void>((resolve) => { release = resolve; });\n  return { promise, release };\n}\n\ndescribe('upload tag reconciliation wave', () => {\n  it('coalesces chained and concurrent row work into one settled refresh', async () => {\n    const gate = deferred();\n    let firstSteps = 0;\n    let secondSteps = 0;\n    let refreshes = 0;\n    const wave = createUploadTagReconciliationWave(async () => { refreshes += 1; });\n    const first = {};\n    const second = {};\n\n    const firstRun = wave.run(first, async () => {\n      firstSteps += 1;\n      if (firstSteps === 1) {\n        await gate.promise;\n        return true;\n      }\n      return false;\n    });\n    const duplicateRun = wave.run(first, async () => {\n      throw new Error('duplicate row run should not start');\n    });\n    const secondRun = wave.run(second, async () => {\n      secondSteps += 1;\n      await gate.promise;\n      return false;\n    });\n\n    expect(duplicateRun).toBe(firstRun);\n    expect(wave.isRunning(first)).toBe(true);\n    gate.release();\n    await Promise.all([firstRun, secondRun]);\n\n    expect(firstSteps).toBe(2);\n    expect(secondSteps).toBe(1);\n    expect(refreshes).toBe(1);\n    expect(wave.isRunning(first)).toBe(false);\n    expect(wave.isRunning(second)).toBe(false);\n  });\n\n  it('runs a follow-up refresh when another wave settles during an in-flight refresh', async () => {\n    const refreshGate = deferred();\n    let refreshes = 0;\n    const wave = createUploadTagReconciliationWave(async () => {\n      refreshes += 1;\n      if (refreshes === 1) await refreshGate.promise;\n    });\n\n    const firstRun = wave.run({}, async () => false);\n    await Promise.resolve();\n    await Promise.resolve();\n    expect(refreshes).toBe(1);\n\n    const secondRun = wave.run({}, async () => false);\n    await Promise.resolve();\n    refreshGate.release();\n    await Promise.all([firstRun, secondRun]);\n\n    expect(refreshes).toBe(2);\n  });\n});\n''')
