/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get running build identity. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Running server version and source revision. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            version: string;
                            revision: string;
                            dirty: boolean;
                            development: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server is reachable. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a DB-backed browser session. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Authenticated user, capabilities, CSRF token, and HttpOnly session cookie. */
                200: {
                    headers: {
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthMeResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session and clear its cookie. */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
                    "X-Gooru-CSRF": components["parameters"]["CSRF"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session revoked. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the current user, capabilities, and a fresh CSRF token. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current session details. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthMeResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the current user's password. */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
                    "X-Gooru-CSRF": components["parameters"]["CSRF"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description Password changed. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/file-selections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an immutable snapshot of the files matching a library query. */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
                    "X-Gooru-CSRF": components["parameters"]["CSRF"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FileSelectionCreateRequest"];
                };
            };
            responses: {
                /** @description Immutable file selection snapshot created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileSelectionCreateResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/file-selections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Release an immutable file selection snapshot. */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
                    "X-Gooru-CSRF": components["parameters"]["CSRF"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Snapshot released or already absent. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/file-selections/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Return which candidate file IDs belong to an immutable selection snapshot. */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
                    "X-Gooru-CSRF": components["parameters"]["CSRF"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FileSelectionMembersRequest"];
                };
            };
            responses: {
                /** @description Candidate IDs that are members of the snapshot. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileSelectionMembersResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description Selection snapshot expired or is no longer available. */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/file-downloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prepare a short-lived bulk download for a selected set of files.
         * @description Creates an owner-scoped download ticket for either explicit file IDs or an immutable selection snapshot with include/exclude deltas. The ticket is then consumed through the streaming GET endpoint so browsers do not need to buffer the ZIP in JavaScript.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
                    "X-Gooru-CSRF": components["parameters"]["CSRF"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FileDownloadRequest"];
                };
            };
            responses: {
                /** @description Bulk download ticket created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileDownloadCreateResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description Referenced selection snapshot expired or is no longer available. */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/file-downloads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream a prepared selected-file download.
         * @description Streams a single selected original with the same semantics as the per-file download endpoint. Selections of two or more files stream directly into a ZIP using stored entries (no compression). ZIP archives are generated incrementally and may omit Content-Length.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A direct original response for one selected file, or a streaming ZIP archive for multiple selected files. */
                200: {
                    headers: {
                        "Content-Disposition"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description Download ticket or referenced selection snapshot expired. */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tracked files for browser grids. */
        get: {
            parameters: {
                query?: {
                    query?: string;
                    limit?: number;
                    page_token?: string;
                    sort?: "added" | "name" | "modified" | "size" | "kind";
                    order?: "asc" | "desc";
                    include_facets?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of tracked files. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileListResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Untrack or physically delete a selected set of files.
         * @description Accepts the same explicit-ID or query-with-exclusions selector used by bulk UI actions. Strict physical deletion is accepted only when every selected file is inside configured upload targets. After explicit confirmation, delete_or_untrack deletes managed files while only untracking files outside configured upload targets.
         */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
                    "X-Gooru-CSRF": components["parameters"]["CSRF"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FileRemovalRequest"];
                };
            };
            responses: {
                /** @description Selected file locations were removed. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileRemovalResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description Physical deletion was requested for a selection containing files outside configured upload targets. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search tracked files with query state in the request body.
         * @description Read-only alternative to GET /files for clients that must keep free-form library query text out of browser/proxy URL histories. Uses the same search service and pagination semantics as GET /files.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FileSearchRequest"];
                };
            };
            responses: {
                /** @description Page of tracked files. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileListResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one tracked file by opaque file ID. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tracked file details. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["File"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Untrack a file location or delete managed uploaded content.
         * @description Untrack removes only the selected database location. Delete also removes the underlying file, but is accepted only for paths inside configured upload targets.
         */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
                    "X-Gooru-CSRF": components["parameters"]["CSRF"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @default untrack
                         * @enum {string}
                         */
                        mode?: "untrack" | "delete";
                    };
                };
            };
            responses: {
                /** @description File location was untracked. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteFileResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Physical deletion was requested for a file outside configured upload targets. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a cacheable thumbnail for a tracked file. */
        get: {
            parameters: {
                query?: {
                    /** @description Requested thumbnail size. Must be one of the configured thumbnail_sizes values. */
                    size?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Thumbnail image derivative. */
                200: {
                    headers: {
                        "Cache-Control"?: string;
                        "X-Gooru-Cache"?: "hit" | "miss";
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": string;
                        "image/png": string;
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                415: components["responses"]["UnsupportedMedia"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a cacheable preview derivative for a tracked file. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Preview image derivative. */
                200: {
                    headers: {
                        "Cache-Control"?: string;
                        "X-Gooru-Cache"?: "hit" | "miss";
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": string;
                        "image/png": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                415: components["responses"]["UnsupportedMedia"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream original content for a tracked file.
         * @description Supports HTTP range requests for browser audio and video seeking.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @example bytes=0-1048575 */
                    Range?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Full original file content. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                /** @description Partial original file content. */
                206: {
                    headers: {
                        "Content-Range"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Get original content metadata for a tracked file.
         * @description Returns the same original-media headers and range semantics as GET without a response body.
         */
        head: {
            parameters: {
                query?: never;
                header?: {
                    /** @example bytes=0-1048575 */
                    Range?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Original file metadata. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Partial original file metadata. */
                206: {
                    headers: {
                        "Content-Range"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        patch?: never;
        trace?: never;
    };
    "/files/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download original content for a tracked file.
         * @description Streams original media with an attachment content disposition and range support.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    Range?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Full original file download. */
                200: {
                    headers: {
                        "Content-Disposition"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                /** @description Partial original file download. */
                206: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Get original download metadata for a tracked file.
         * @description Returns the same attachment and range headers as GET without a response body.
         */
        head: {
            parameters: {
                query?: never;
                header?: {
                    Range?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Original file download metadata. */
                200: {
                    headers: {
                        "Content-Disposition"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Partial original file download metadata. */
                206: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        patch?: never;
        trace?: never;
    };
    "/comics/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List naturally ordered image pages in a CBZ comic. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Comic page manifest. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ComicManifest"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                415: components["responses"]["UnsupportedMedia"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comics/{id}/{page}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream one naturally ordered image page from a CBZ comic. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    page: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Requested comic page image. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": string;
                        "image/png": string;
                        "image/gif": string;
                        "image/webp": string;
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                415: components["responses"]["UnsupportedMedia"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace tags on selected files. */
        put: {
            parameters: {
                query?: never;
                header: {
                    /** @description Set to respond-async to accept the mutation asynchronously; poll the returned durable operation as documented by the endpoint. */
                    Prefer?: components["parameters"]["PreferAsync"];
                    /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
                    "X-Gooru-CSRF": components["parameters"]["CSRF"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TagMutationRequest"];
                };
            };
            responses: {
                200: components["responses"]["TagMutation"];
                202: components["responses"]["AsyncOperation"];
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        /** Add tags to selected files. */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Set to respond-async to accept the mutation asynchronously; poll the returned durable operation as documented by the endpoint. */
                    Prefer?: components["parameters"]["PreferAsync"];
                    /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
                    "X-Gooru-CSRF": components["parameters"]["CSRF"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TagMutationRequest"];
                };
            };
            responses: {
                200: components["responses"]["TagMutation"];
                202: components["responses"]["AsyncOperation"];
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        /**
         * Remove tags from selected files.
         * @description If tags is empty, all tags are removed from the selected files.
         */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description Set to respond-async to accept the mutation asynchronously; poll the returned durable operation as documented by the endpoint. */
                    Prefer?: components["parameters"]["PreferAsync"];
                    /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
                    "X-Gooru-CSRF": components["parameters"]["CSRF"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TagMutationRequest"];
                };
            };
            responses: {
                200: components["responses"]["TagMutation"];
                202: components["responses"]["AsyncOperation"];
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seal WebUI library state into an opaque protected-mode token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BrowserURLState"];
                };
            };
            responses: {
                /** @description Protected state token */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            token: string;
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui-state/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve an opaque protected-mode WebUI state token */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Restored library state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BrowserURLState"];
                    };
                };
                404: components["responses"]["NotFound"];
                /** @description Protected state token expired */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload-targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configured upload targets. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Configured upload targets without filesystem paths. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadTargetsResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload files into a configured upload target and import them. */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Set to respond-async to accept the mutation asynchronously; poll the returned durable operation as documented by the endpoint. */
                    Prefer?: components["parameters"]["PreferAsync"];
                    /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
                    "X-Gooru-CSRF": components["parameters"]["CSRF"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        files: string[];
                        /**
                         * @description Override the selected upload target's added-at strategy for this submission.
                         * @enum {string}
                         */
                        added_at_strategy?: "queue" | "reverse_queue" | "modtime";
                        /** @description Client-captured queue timestamps in Unix milliseconds, one per file. */
                        queue_time_ms?: number[];
                        /**
                         * Format: int64
                         * @description Earliest client-captured queue timestamp in this submission; used with `queue_last_time_ms` to reverse queues consistently across one-file async worker requests.
                         */
                        queue_first_time_ms?: number;
                        /**
                         * Format: int64
                         * @description Latest client-captured queue timestamp in this submission; used with `queue_first_time_ms` to reverse queues consistently across one-file async worker requests.
                         */
                        queue_last_time_ms?: number;
                        /** @description Stable queue indexes, one per file. */
                        queue_index?: number[];
                        /** @description Queue batch size, one per file. */
                        queue_total?: number[];
                        /** @description Source modification timestamps in Unix milliseconds, in the same order as `files`. Invalid or missing entries are treated as unavailable. */
                        source_modtime_ms?: number[];
                        /** @description Configured upload target ID. Defaults to the first configured target. */
                        target_id?: string;
                        /**
                         * @description How to handle a requested filename that already exists in the target; omitted values default to rename, while error rejects the request on a path collision.
                         * @default rename
                         * @enum {string}
                         */
                        conflict_policy?: "rename" | "error";
                        /** @description Space- or comma-separated fallback initial tags applied to files that do not provide item_tags. */
                        tags?: string;
                        /** @description Per-file initial tag strings aligned with files. Each entry accepts space- or comma-separated tags; an explicit empty entry means no tags for that file and suppresses fallback tags. Omit item_tags entirely to apply fallback tags to every file. */
                        item_tags?: string[];
                    };
                };
            };
            responses: {
                /** @description Synchronous upload/import result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadImportResponse"];
                    };
                };
                202: components["responses"]["AsyncOperation"];
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                413: components["responses"]["PayloadTooLarge"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List known tags. */
        get: {
            parameters: {
                query?: {
                    counts?: boolean;
                    /** @description Maximum tags to return. Defaults to 200 and is capped at 500. */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tags, optionally with counts. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TagListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/namespaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tag namespaces. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Known tag namespaces. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NamespacesResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return tag autocomplete suggestions. */
        get: {
            parameters: {
                query?: {
                    /** @description Current token prefix. Use namespace:value prefixes such as `kind:` for value suggestions. */
                    q?: string;
                    /** @description Existing query expression; already-present tags are filtered from suggestions when parseable. */
                    existing?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Matching tag suggestions. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuggestionsResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Return search suggestions with free-form query state in the request body. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SuggestionRequest"];
                };
            };
            responses: {
                /** @description Search suggestions. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuggestionsResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saved-searches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List saved searches for the current user. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user's saved searches. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SavedSearchesResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create a saved search for the current user. */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
                    "X-Gooru-CSRF": components["parameters"]["CSRF"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SavedSearchRequest"];
                };
            };
            responses: {
                /** @description Saved search created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SavedSearch"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saved-searches/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace the saved-search order for the current user. */
        put: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
                    "X-Gooru-CSRF": components["parameters"]["CSRF"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SavedSearchReorderRequest"];
                };
            };
            responses: {
                /** @description Saved-search order replaced. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saved-searches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace one saved search. */
        put: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
                    "X-Gooru-CSRF": components["parameters"]["CSRF"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SavedSearchRequest"];
                };
            };
            responses: {
                /** @description Saved search updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SavedSearch"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** Delete one saved search. */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
                    "X-Gooru-CSRF": components["parameters"]["CSRF"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Saved search deleted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maintenance-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List manually runnable maintenance jobs.
         * @description Returns the backend-owned catalog of maintenance jobs that an administrator can start manually from the Jobs view.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Manually runnable maintenance jobs. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MaintenanceJobListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maintenance-jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a maintenance job.
         * @description Requests the selected backend-owned maintenance job through the durable background job system. A 200 response with created=false means an equivalent job is already pending or running. Explicit no-work requests still create an observable durable job that completes normally.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
                    "X-Gooru-CSRF": components["parameters"]["CSRF"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description An equivalent maintenance job is already pending or running; no duplicate durable work was created. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MaintenanceJobRunResponse"];
                    };
                };
                /** @description New durable maintenance work was queued. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MaintenanceJobRunResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description Maintenance job ID is not registered. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Maintenance work could not be queued. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List durable background operations. */
        get: {
            parameters: {
                query?: {
                    /** @description Specific durable operation IDs to return. May be repeated; at most 64 unique IDs are accepted. Completed results are included for this bounded status-batch form. */
                    id?: string[];
                    limit?: number;
                    /** @description Zero-based number of visible operations to skip. */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Visible durable operations matching the request. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackgroundOperationListResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Clear visible terminal durable operation history.
         * @description Removes completed, failed, and canceled visible operations together with their terminal child task history. Pending/running operations, hidden implementation operations, and operations with active child tasks are retained.
         */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
                    "X-Gooru-CSRF": components["parameters"]["CSRF"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Terminal operation history cleared. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: int64 */
                            cleared: number;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream durable background operation change signals.
         * @description Sends payload-free `operations` server-sent events after committed Jobs-visible operation or task state changes, plus an initial reconciliation signal and periodic keepalive comments. Requires an authenticated administrator session.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Long-lived server-sent event stream of Jobs invalidation signals. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations/cancel-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancel all visible active durable background operations.
         * @description Cancels every visible pending or running durable operation. Terminal history and hidden implementation operations are not affected.
         */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
                    "X-Gooru-CSRF": components["parameters"]["CSRF"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active visible operations canceled. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            canceled: number;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description Active operations could not be listed or canceled. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one durable background operation. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Durable operation state, including a structured result when completed and available. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackgroundOperation"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Cancel an active durable background operation. */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
                    "X-Gooru-CSRF": components["parameters"]["CSRF"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Operation canceled. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackgroundOperation"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        ChangePasswordRequest: {
            /** Format: password */
            current_password: string;
            /** Format: password */
            new_password: string;
        };
        AuthMeResponse: {
            user: components["schemas"]["User"];
            capabilities: {
                upload: boolean;
                tag: boolean;
                delete: boolean;
                admin: boolean;
            };
            csrf_token?: string;
        };
        User: {
            id: string;
            username: string;
            /** @enum {string} */
            role: "admin";
        };
        FileSearchRequest: {
            query?: string;
            limit?: number;
            page_token?: string;
            /** @enum {string} */
            sort?: "added" | "name" | "modified" | "size" | "kind";
            /** @enum {string} */
            order?: "asc" | "desc";
            include_facets?: boolean;
        };
        SuggestionRequest: {
            q?: string;
            existing?: string;
            limit?: number;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                details?: unknown;
            };
        };
        ComicPage: {
            index: number;
            name: string;
            url: string;
        };
        ComicManifest: {
            pages: components["schemas"]["ComicPage"][];
        };
        FileSelectionCreateRequest: {
            /** @description Library query to snapshot. Empty is treated as *. */
            query?: string;
        };
        FileSelectionCreateResponse: {
            id: string;
            count: number;
        };
        FileSelectionMembersRequest: {
            file_ids: string[];
        };
        FileSelectionMembersResponse: {
            file_ids: string[];
        };
        /** @description Exactly one of file_ids or selection_id must be provided. Include/exclude deltas are valid only with selection_id. */
        FileDownloadRequest: {
            file_ids?: string[];
            /** @description Immutable selection snapshot ID. Mutually exclusive with file_ids. */
            selection_id?: string;
            /** @description Explicit additions to a selection snapshot. Valid only with selection_id. */
            include_file_ids?: string[];
            /** @description Explicit exclusions from a selection snapshot. Valid only with selection_id. */
            exclude_file_ids?: string[];
        };
        FileDownloadCreateResponse: {
            id: string;
            /** @description Same-origin URL that streams the prepared ZIP archive. */
            url: string;
        };
        FileRemovalSelector: {
            file_ids?: string[];
            query?: string;
            /** @description Immutable selection snapshot ID. Mutually exclusive with file_ids and query. */
            selection_id?: string;
            /** @description Explicit additions to a selection snapshot. Valid only with selection_id. */
            include_file_ids?: string[];
            /** @description Explicit exclusions from a query or selection snapshot. */
            exclude_file_ids?: string[];
        };
        FileRemovalRequest: components["schemas"]["FileRemovalSelector"] & {
            /** @enum {string} */
            mode: "untrack" | "delete" | "delete_or_untrack";
        };
        FileRemovalResponse: {
            /** @enum {string} */
            mode: "untrack" | "delete" | "delete_or_untrack";
            selector: components["schemas"]["FileRemovalSelector"];
            removed_locations: number;
        };
        TagMutationRequest: {
            /** @description Opaque file IDs. Exactly one of file_ids or query must be provided. */
            file_ids?: string[];
            /** @description Query selector. Exactly one of file_ids or query must be provided. */
            query?: string;
            /** @description Immutable selection snapshot ID. Mutually exclusive with file_ids and query. */
            selection_id?: string;
            /** @description Explicit additions to a selection snapshot. Valid only with selection_id. */
            include_file_ids?: string[];
            /** @description Explicit exclusions from a query or selection snapshot. */
            exclude_file_ids?: string[];
            tags: string[];
            /** @default false */
            verbose: boolean;
        };
        TagMutationResponse: {
            /** @enum {string} */
            operation: "add" | "set" | "remove";
            selector: {
                file_ids?: string[];
                query?: string;
                exclude_file_ids?: string[];
            };
            matched_files?: number;
            affected_count: number;
            notifications?: {
                /** @enum {string} */
                kind: "move_detected" | "modified" | "unknown";
                original_path?: string;
                old_path?: string;
                new_path?: string;
                orphaned_tags?: string[];
            }[];
        };
        UploadImportResponse: {
            files: {
                /** @description Opaque stable file-location identifier for imported or existing library content. Omitted when no library file identity is available. */
                id?: string;
                name: string;
                /** Format: int64 */
                size: number;
                target_id: string;
                /** @enum {string} */
                status: "uploaded" | "imported" | "duplicate_existing" | "duplicate_in_batch" | "skipped" | "error";
                error?: string;
            }[];
            affected_count: number;
            notifications?: {
                /** @enum {string} */
                kind: "move_detected" | "modified" | "unknown";
                original_path?: string;
                old_path?: string;
                new_path?: string;
                orphaned_tags?: string[];
            }[];
        };
        UploadTargetsResponse: {
            items: {
                id: string;
                name: string;
                /**
                 * @description Default added-at strategy configured for this upload target.
                 * @enum {string}
                 */
                added_at_strategy: "queue" | "reverse_queue" | "modtime";
                /** @description Visible editable tags and -tag exclusions prefilled for this upload target. */
                default_tags?: string[];
            }[];
        };
        MaintenanceJob: {
            id: string;
            name: string;
            description: string;
            /** @description True when this maintenance job already has a pending or running durable operation. */
            running: boolean;
        };
        MaintenanceJobListResponse: {
            items: components["schemas"]["MaintenanceJob"][];
        };
        MaintenanceJobRunResponse: {
            job: components["schemas"]["MaintenanceJob"];
            /** @description True when this invocation created new durable maintenance work. */
            created: boolean;
        };
        BackgroundOperation: {
            id: string;
            kind: string;
            /** @enum {string} */
            status: "pending" | "running" | "completed" | "failed" | "canceled";
            /**
             * @description Optional user-visible lifecycle stage for upload_import operations. Receiving is active synchronous request-body work; importing is durable queued/running processing.
             * @enum {string}
             */
            stage?: "receiving" | "importing";
            /** Format: int64 */
            progress_total: number;
            /** Format: int64 */
            progress_completed: number;
            /**
             * Format: int64
             * @description For upload_import operations, number of leading upload files whose analysis stage has completed. Omitted for other operation kinds.
             */
            progress_completed_prefix?: number;
            /** Format: int64 */
            progress_failed: number;
            /**
             * Format: double
             * @description Optional overall operation progress fraction. Uploads omit this while receiving when the request length is unknown.
             */
            progress?: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string;
            error_code?: string;
            error_message?: string;
            result?: unknown;
        };
        BackgroundOperationListResponse: {
            items: components["schemas"]["BackgroundOperation"][];
        };
        BrowserURLState: {
            query?: string;
            kind?: string;
            /** @enum {string} */
            sort?: "added" | "name" | "modified" | "size" | "kind";
            /** @enum {string} */
            order?: "asc" | "desc";
            file_id?: string;
        };
        FileListResponse: {
            files: components["schemas"]["File"][];
            next_page_token?: string;
            previous_page_token?: string;
            /** @description Total number of files matching the current query. */
            total_count: number;
            /** @description Total tracked files in the library. */
            library_count: number;
            facets?: components["schemas"]["Facets"];
        };
        Facets: {
            kind?: components["schemas"]["FacetValue"][];
        };
        FacetValue: {
            value: string;
            count: number;
        };
        File: {
            /** @description Opaque stable file-location identifier. */
            id: string;
            /** @description Content fingerprint for the tracked file. */
            content_id: string;
            name: string;
            /** @description Absolute filesystem path. Omitted unless server path exposure is enabled. */
            path?: string;
            /** @description Display-only non-absolute path hint, such as the last directory plus filename. */
            safe_display_path: string;
            /** Format: int64 */
            size: number;
            /** Format: date-time */
            added_at: string;
            /** Format: date-time */
            modified_time: string;
            media_type: string;
            /** @enum {string} */
            media_kind: "photo" | "video" | "gif" | "audio" | "comic" | "other";
            /**
             * @description Backend-owned indication of whether the built-in viewer supports this media type.
             * @enum {string}
             */
            viewer_support: "supported" | "unsupported_media_type";
            metadata: components["schemas"]["MediaMetadata"];
            tags: string[];
            media_urls: components["schemas"]["MediaURLs"];
            /** @description True when the file path is inside a configured upload target and may be physically deleted through the API. */
            can_delete: boolean;
        };
        /** @description Optional media metadata. Fields are omitted when unavailable or extraction fails. */
        MediaMetadata: {
            image_width?: number;
            image_height?: number;
            video_width?: number;
            video_height?: number;
            /** Format: double */
            video_duration?: number;
            /** Format: double */
            audio_duration?: number;
            frame_count?: number;
            /** @description Number of displayable pages for paged media such as CBZ comics. */
            page_count?: number;
        };
        MediaURLs: {
            thumbnail: string;
            preview: string;
            content: string;
            download: string;
        };
        TagListResponse: {
            tags: components["schemas"]["Tag"][];
            /** @description Total tracked files in the library. */
            library_count: number;
            facets?: components["schemas"]["Facets"];
        };
        Tag: {
            name: string;
            namespace?: string;
            value?: string;
            count?: number;
        };
        DeleteFileResponse: {
            /** @enum {string} */
            mode: "untrack" | "delete";
            removed_locations: number;
        };
        MetaTag: {
            name: string;
            syntax: string;
            hint: string;
            requires_value: boolean;
        };
        SuggestionsResponse: {
            items: components["schemas"]["Tag"][];
            /** @description Complete backend-owned catalog of supported query metatags. */
            meta_tags: components["schemas"]["MetaTag"][];
        };
        NamespacesResponse: {
            items: string[];
        };
        SavedSearchReorderRequest: {
            ids: string[];
        };
        SavedSearchRequest: {
            name: string;
            query: string;
            /**
             * @default added
             * @enum {string}
             */
            sort: "added" | "name" | "modified" | "size" | "kind";
            /**
             * @default desc
             * @enum {string}
             */
            order: "asc" | "desc";
        };
        SavedSearch: {
            id: string;
            name: string;
            query: string;
            /** @enum {string} */
            sort: "added" | "name" | "modified" | "size" | "kind";
            /** @enum {string} */
            order: "asc" | "desc";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        SavedSearchesResponse: {
            items: components["schemas"]["SavedSearch"][];
        };
    };
    responses: {
        /** @description Missing or invalid session cookie. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request is forbidden, including failed CSRF validation or insufficient privileges. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request body or uploaded file is too large. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Service is temporarily unavailable, including a full durable-operation admission window. */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Aggregate tag mutation result. */
        TagMutation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["TagMutationResponse"];
            };
        };
        /** @description Mutation was accepted as a durable background operation. */
        AsyncOperation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BackgroundOperation"];
            };
        };
        /** @description The requested media derivative cannot be generated for this file. */
        UnsupportedMedia: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description CSRF token returned by /auth/login or /auth/me. Required for cookie-authenticated mutating requests. */
        CSRF: string;
        /** @description Set to respond-async to accept the mutation asynchronously; poll the returned durable operation as documented by the endpoint. */
        PreferAsync: "respond-async";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
