DROP TRIGGER IF EXISTS tag_key_kind_counts_metadata_delete;
DROP TRIGGER IF EXISTS tag_key_kind_counts_metadata_update;
DROP TRIGGER IF EXISTS tag_key_kind_counts_metadata_insert;
DROP TRIGGER IF EXISTS tag_key_kind_counts_location_extension_update;
DROP TRIGGER IF EXISTS tag_key_kind_counts_location_delete;
DROP TRIGGER IF EXISTS tag_key_kind_counts_location_insert;
DROP TRIGGER IF EXISTS tag_key_kind_counts_content_tag_delete;
DROP TRIGGER IF EXISTS tag_key_kind_counts_content_tag_insert;
DROP TABLE IF EXISTS tag_key_kind_counts;
