package query

import (
	"fmt"
	"strings"
)

// SQLBuilder transforms a query AST into a SQL query string and arguments.
type SQLBuilder struct {
	query        strings.Builder
	args         []interface{}
	aliasCounter int
}

// newAlias creates a unique alias for a derived table (e.g., t0, t1, ...).
func (b *SQLBuilder) newAlias() string {
	alias := fmt.Sprintf("t%d", b.aliasCounter)
	b.aliasCounter++
	return alias
}

// Build generates the SQL query from the AST.
func Build(expr *Expression) (string, []interface{}) {
	if expr == nil || len(expr.Or) == 0 {
		return "", nil
	}
	b := &SQLBuilder{}
	b.buildExpression(expr)
	return b.query.String(), b.args
}

// buildExpression handles OR nodes. If there are multiple OR operands, the entire
// resulting compound query is wrapped in a derived table to make it a valid SELECT statement.
func (b *SQLBuilder) buildExpression(expr *Expression) {
	isCompound := len(expr.Or) > 1
	if isCompound {
		b.query.WriteString("SELECT hash FROM (")
	}

	for i, andTerm := range expr.Or {
		if i > 0 {
			b.query.WriteString(" UNION ")
		}
		b.buildAndTerm(andTerm)
	}

	if isCompound {
		b.query.WriteString(fmt.Sprintf(") AS %s", b.newAlias()))
	}
}

// buildAndTerm handles AND nodes. It constructs a single SELECT statement with
// IN and NOT IN clauses, which is generally more performant than using INTERSECT
// as it gives the query planner more optimization opportunities.
func (b *SQLBuilder) buildAndTerm(andTerm *AndTerm) {
	// If there's only one term, we don't need complex AND logic; just build the term.
	if len(andTerm.And) == 1 {
		b.buildTerm(andTerm.And[0])
		return
	}

	var positiveTerms []*Term
	var negativeTerms []*Term

	for _, term := range andTerm.And {
		if term.Not {
			negativeTerms = append(negativeTerms, term)
		} else {
			positiveTerms = append(positiveTerms, term)
		}
	}

	if len(positiveTerms) == 0 {
		// Case: The query is composed entirely of negative terms, e.g., "-a -b".
		// We start with the set of all content and filter it down.
		b.query.WriteString("SELECT hash FROM contents WHERE 1=1")
		for _, term := range negativeTerms {
			b.query.WriteString(" AND hash NOT IN (")
			b.buildFactor(term.Factor)
			b.query.WriteString(")")
		}
		return
	}

	// Case: The query has at least one positive term, e.g., "a & b & -c".
	// We use the first positive term as the base set to query from. This is
	// often a good heuristic, as it immediately limits the scope.
	b.query.WriteString("SELECT hash FROM (")
	b.buildFactor(positiveTerms[0].Factor)
	b.query.WriteString(fmt.Sprintf(") AS %s WHERE 1=1", b.newAlias()))

	// Filter this base set by requiring matches in all other positive terms.
	for i := 1; i < len(positiveTerms); i++ {
		b.query.WriteString(" AND hash IN (")
		b.buildFactor(positiveTerms[i].Factor)
		b.query.WriteString(")")
	}

	// Further filter the set by excluding matches from all negative terms.
	for _, term := range negativeTerms {
		b.query.WriteString(" AND hash NOT IN (")
		b.buildFactor(term.Factor)
		b.query.WriteString(")")
	}
}

// buildTerm handles NOT nodes. A negated term selects from all content hashes that
// are not present in the sub-query generated by the negated factor.
func (b *SQLBuilder) buildTerm(term *Term) {
	if term.Not {
		// This uses `NOT IN` which is vastly more performant than the previous
		// `SELECT ... FROM contents EXCEPT SELECT ...` which forced a full table scan.
		// The database can now use a more efficient anti-join or NOT EXISTS plan.
		b.query.WriteString("SELECT hash FROM contents WHERE hash NOT IN (")
		b.buildFactor(term.Factor)
		b.query.WriteString(")")
	} else {
		b.buildFactor(term.Factor)
	}
}

// buildFactor handles the base units: a tag or a user-defined sub-expression.
func (b *SQLBuilder) buildFactor(factor *Factor) {
	if factor.SubExpr != nil {
		// A user-defined sub-expression is evaluated recursively. The resulting SQL
		// is already a valid SELECT statement due to the logic in the other build functions.
		b.buildExpression(factor.SubExpr)
	} else if factor.Tag != nil {
		b.buildTagQuery(*factor.Tag)
	}
}

// buildTagQuery generates the base, simple SELECT statement for a single tag,
// handling both normal tags and virtual metadata tags.
func (b *SQLBuilder) buildTagQuery(tagStr string) {
	// Handle meta-tags first, as they don't follow the key:value structure.
	if strings.HasPrefix(tagStr, "@") {
		switch tagStr {
		case "@tagged":
			b.query.WriteString(`SELECT DISTINCT content_hash as hash FROM content_tags`)
		// In the future, other meta-tags like @orphaned could be added here.
		default:
			// For now, treat unknown meta-tags as "no results".
			b.query.WriteString(`SELECT NULL as hash WHERE 0`)
		}
		return
	}

	parsed := ParseTag(tagStr)

	switch parsed.Key {
	case "ext":
		// Query against the indexed, lowercase extension in the locations table.
		b.query.WriteString(`SELECT content_hash as hash FROM locations WHERE lower(extension) = lower(?)`)
		value := parsed.Value
		// Add leading dot to extension if missing, for user convenience.
		if value != "" && !strings.HasPrefix(value, ".") {
			value = "." + value
		}
		b.args = append(b.args, value)
	// Add other virtual tags like 'size', 'path', etc. here in the future.
	default:
		// Default behavior for user-defined tags
		if parsed.Value == "*" {
			// Query for a key with any non-empty value (e.g., "location:*").
			b.query.WriteString(`SELECT ct.content_hash as hash FROM content_tags ct JOIN tags t ON ct.tag_id = t.id WHERE t.key = ? AND t.value != ''`)
			b.args = append(b.args, parsed.Key)
		} else if parsed.Value != "" {
			// Query for a specific key:value pair (e.g., "location:home").
			b.query.WriteString(`SELECT ct.content_hash as hash FROM content_tags ct JOIN tags t ON ct.tag_id = t.id WHERE t.key = ? AND t.value = ?`)
			b.args = append(b.args, parsed.Key, parsed.Value)
		} else {
			// This is the ambiguous case: `location` vs `location:`
			if strings.HasSuffix(tagStr, ":") {
				// The user explicitly typed the colon, so they want an empty value (e.g., "location:").
				b.query.WriteString(`SELECT ct.content_hash as hash FROM content_tags ct JOIN tags t ON ct.tag_id = t.id WHERE t.key = ? AND t.value = ''`)
				b.args = append(b.args, parsed.Key)
			} else {
				// Query for a key, regardless of value (e.g., "location").
				b.query.WriteString(`SELECT ct.content_hash as hash FROM content_tags ct JOIN tags t ON ct.tag_id = t.id WHERE t.key = ?`)
				b.args = append(b.args, parsed.Key)
			}
		}
	}
}
